// learn_vue/student/todo_composition/src/components/TodoListItem.vue
<script setup>
import { onMounted } from "vue";

const props = defineProps({
  todo: {
    type: Object,
  },
});
const emit = defineEmits(["toggleTodo", "deleteTodo"]);
onMounted(() => {
  console.log("todoListItem");
});
</script>
<template>
  <li
    class="flex items-center justify-between p-3 border-b hover:bg-gray-100 transition-colors"
  >
    <div class="flex items-center">
      <input
        type="checkbox"
        :class="`mr-3 h-4 w-4 text-blue-500 focus:ring-blue-400`"
        :checked="todo.done"
        @change="emit('toggleTodo', todo.id)"
      />
      <span>{{ todo.text }}</span>
    </div>
    <button
      class="text-red-500 hover:text-red-700 ml-4"
      @click="emit('deleteTodo', todo.id)"
    >
      Delete
    </button>
  </li>
</template>

// learn_react/09/Todo_props/src/components/TodoListItem.tsx
import React from "react";
import { twMerge } from "tailwind-merge";

export default React.memo(function TodoListItem({
  todo,
  toggleTodo,
  deleteTodo,
}: {
  key: number;
  todo: TodoItem;
  toggleTodo: (id: number) => void;
  deleteTodo: (id: number) => void;
}) {
  console.log("TodoListItem Rendering");
  return (
    <li className="flex items-center justify-between p-3 border-b hover:bg-gray-100 transition-colors">
      <div className="flex items-center">
        <input
          type="checkbox"
          className="mr-3 h-4 w-4 text-blue-500 focus:ring-blue-400"
          checked={todo.done}
          onChange={() => toggleTodo(todo.id)}
        />
        <span className={twMerge(todo.done && "line-through")}>
          {todo.text}
        </span>
      </div>
      <button
        className="text-red-500 hover:text-red-700 ml-4"
        onClick={() => deleteTodo(todo.id)}
      >
        Delete
      </button>
    </li>
  );
});
