// learn-vue/student/todo_list/src/components/TodoListItem.vue
<script setup>
import { inject } from "vue";

const todos = inject("todos");
const removeTodo = inject("removeTodo");
const toggleTodo = inject("toggleTodo");
</script>
<template>
  <li
    class="flex items-center justify-between p-3 border-b hover:bg-gray-100 transition-colors"
    v-for="todo in todos"
    :key="todo.id"
  >
    <div class="flex items-center">
      <input
        type="checkbox"
        :class="`mr-3 h-4 w-4 text-blue-500 focus:ring-blue-400`"
        :checked="todo.completed"
        @change="toggleTodo(todo.id)"
      />
      <span :class="`${todo.completed ? 'line-through' : ''}`">{{
        todo.text
      }}</span>
    </div>
    <button
      class="text-red-500 hover:text-red-700 ml-4"
      @click="removeTodo(todo.id)"
    >
      Delete
    </button>
  </li>
</template>

// learn-react/06/6-과제/todo/src/components/TodoListItem.tsx
import {twMerge} from "tailwind-merge";

export default function TodoListItem({
  todo,
  toggleTodo,
  deleteTodo,
}: {
  key: number;
  todo: TodoItem;
  toggleTodo: (id: number) => void;
  deleteTodo: (id: number) => void;
}) {
  return (
    <li className='flex items-center justify-between p-3 border-b hover:bg-gray-100 transition-colors'>
      <div className='flex items-center'>
        <input
          type='checkbox'
          className='mr-3 h-4 w-4 text-blue-500 focus:ring-blue-400'
          checked={todo.done}
          onChange={() => toggleTodo(todo.id)}
        />
        <span className={twMerge(todo.done && "line-through")}>{todo.text}</span>
      </div>
      <button className='text-red-500 hover:text-red-700 ml-4' onClick={() => deleteTodo(todo.id)}>
        Delete
      </button>
    </li>
  );
}
