// learn-react/08/1/src/components/CountButtons.tsx
import { useCountStore } from "../stores/countStores";

export default function CountButtons() {
  const decrement = useCountStore((state) => state.decrement);
  const reset = useCountStore((state) => state.reset);
  const increment = useCountStore((state) => state.increment);
  return (
    <>
      <button onClick={decrement}>-</button>
      <button onClick={reset}>0</button>
      <button onClick={increment}>+</button>
    </>
  );
}

// learn-vue/03/src/components/CountButtons.vue
<script>
export default {
  name: 'CountButtons',
  props: {
    count: Number,
  },
  data() {
    return {
      localCount: this.count,
    }
  },
  methods: {
    decrement() {
      this.localCount--
      this.$emit('update:count', this.localCount)
    },
    reset() {
      this.localCount = 0
      this.$emit('update:count', this.localCount)
    },
    increment() {
      this.localCount++
      this.$emit('update:count', this.localCount)
    },
  },
}
</script>
<template>
  <button @click="decrement">-</button>
  <button @click="reset">0</button>
  <button @click="increment">+</button>
</template>
<style scoped></style>
