// learn_vue/student/06/todo_pinia/src/components/Todo.vue
<script setup>
import { useTodoStore } from "../stores/todo";
import TodoEditor from "./TodoEditor.vue";
import TodoHeader from "./TodoHeader.vue";
import TodoList from "./TodoList.vue";

const todoStore = useTodoStore();
</script>
<template>
  <div class="max-w-md mx-auto shadow-lg rounded-lg overflow-hidden">
    <TodoHeader />
    <TodoEditor />
    <TodoList />
  </div>
</template>
<style></style>

// learn_react/09/todolist/src/components/Todo.tsx
import { useState } from "react";
import TodoEditor from "./TodoEditor";
import TodoHeader from "./TodoHeader";
import TodoList from "./TodoList";

export default function Todo() {
  const [todo, setTodo] = useState<string[]>([]);

  const addHandler = (input: string) => {
    if (input.length === 0) return;
    setTodo((list) => [...list, input]);
  };

  const deleteHandler = (index: number) => {
    setTodo((list) => list.filter((_, i) => i !== index));
  };
  return (
    <div className="w-[350px] max-w-md mx-auto shadow-lg rounded-lg overflow-hidden bg-white">
      <TodoHeader />
      <TodoEditor clickAdd={addHandler} />
      <TodoList todo={todo} deleteHandler={deleteHandler} />
    </div>
  );
}
