// learn-react/06/6-과제/todo/src/components/Todo.tsx
import {useState} from "react";
import TodoEditor from "./TodoEditor";
import TodoHeader from "./TodoHeader";
import TodoList from "./TodoList";

export default function Todo() {
  const [todos, setTodos] = useState<TodoItem[]>([]);
  const addTodos = (text: string) => {
    setTodos((todos) => [
      ...todos,
      {
        id: Math.random(),
        text,
        done: false,
      },
    ]);
  };
  const toggleTodo = (id: number) => {
    setTodos((todos) => todos.map((todo) => (todo.id === id ? {...todo, done: !todo.done} : todo)));
  };
  const deleteTodo = (id: number) => {
    setTodos((todos) => todos.filter((todo) => todo.id !== id));
  };
  return (
    <div className='w-[350px] max-w-md mx-auto shadow-lg rounded-lg overflow-hidden bg-white'>
      <TodoHeader />
      <TodoEditor addTodos={addTodos} />
      <TodoList todos={todos} toggleTodo={toggleTodo} deleteTodo={deleteTodo} />
    </div>
  );
}

// learn_vue/student/todo_list/src/components/Todo.vue
<script>
import TodoEditor from "./TodoEditor.vue";
import TodoHeader from "./TodoHeader.vue";
import TodoList from "./TodoList.vue";

let id = 0;
export default {
  data() {
    return {
      newTodo: "",
      todos: [],
    };
  },
  components: {
    TodoHeader,
    TodoEditor,
    TodoList,
  },
  methods: {
    addTodo() {
      if (this.newTodo !== "") {
        this.todos.push({ id: id++, text: this.newTodo, done: false });
        this.newTodo = "";
      }
    },
    delTodo(todo) {
      this.todos = this.todos.filter((t) => t.id !== todo.id);
    },
    // toggleTodo(todo) {
    //   todo.done = !todo.done;
    // },
  },
};
</script>
<template>
  <div class="max-w-md mx-auto shadow-lg rounded-lg overflow-hidden">
    <TodoHeader />
    <TodoEditor @add-todo="addTodo" v-model="newTodo" />
    <TodoList @del-todo="delTodo" :todos="todos" />
  </div>
</template>
<style></style>
