// learn-vue/student/todo_composition/src/components/TodoList.vue
<script setup>
import { useTodoStore } from "@/stores/todo";
import TodoListItem from "./TodoListItem.vue";
const todoStores = useTodoStore();
</script>
<template>
  <ul class="divide-y divide-gray-200">
    <TodoListItem
      v-for="todo in todoStores.todos"
      :key="todo.id"
      :todo="todo"
    />
  </ul>
</template>
<style></style>

// learn-react/todos/todo_usereducer/src/components/TodoList.tsx
import TodoListItem from "./TodoListItem";

export default function TodoList({
  todos,
  dispatch,
}: {
  todos: TodoItem[];
  dispatch: Dispatch;
}) {
  return (
    <ul className="divide-y divide-gray-200">
      {todos &&
        todos.map((todo) => (
          <TodoListItem key={todo.id} todo={todo} dispatch={dispatch} />
        ))}
    </ul>
  );
}
