// learn-react/006/homework3/src/components/Todo.tsx
import { useState } from "react";
import TodoEditor from "./TodoEditor";
import TodoHeader from "./TodoHeader";
import TodoList from "./TodoList";

export default function Todo() {
  const initTodos = ["Todo Item Example", "Todo Item Example", "Todo Item Example"];
  const [todos, setTodos] = useState<string[]>(initTodos);
  const addTodo = (todo: string) => {
    setTodos((v) => [...v, todo]);
    // console.log(todo);
  };
  const deleteTodo = (index: number) => {
    setTodos((v) => v.filter((_, i) => i !== index));
  };
  return (
    <div className="w-[350px] max-w-md mx-auto shadow-lg rounded-lg overflow-hidden bg-white">
      <TodoHeader />
      <TodoEditor addTodo={addTodo} />
      <TodoList todos={todos} deleteTodo={deleteTodo} />
    </div>
  );
}

// learn-vue/student/todo_composition/src/components/Todo.vue
<script setup>
import { onMounted, ref, watch } from "vue";
import TodoEditor from "./TodoEditor.vue";
import TodoHeader from "./TodoHeader.vue";
import TodoList from "./TodoList.vue";
import { useTodoStore } from "@/stores/todo";

const todoStores = useTodoStore();
</script>
<template>
  <div class="max-w-md mx-auto shadow-lg rounded-lg overflow-hidden">
    <TodoHeader />
    <TodoEditor @add-todo="todoStores.addTodo" />
    <TodoList
      :todos="todoStores.todos"
      @toggle-todo="todoStores.toggleTodo"
      @delete-todo="todoStores.deleteTodo"
    />
  </div>
</template>
<style></style>
