// learn-vue/04_Homework/src/components/TodoList.vue
<script>
import TodoListItem from "./TodoListItem.vue";

export default {
    components: {
        TodoListItem,
    },
    data() {
        return {};
    },
    props: {
        todos: {
            type: Array,
        },
    },
    emits: ["deleteTodo"],
};
</script>
<template>
    <ul class="divide-y divide-gray-200">
        <TodoListItem
            v-for="todo in todos"
            :key="todo.id"
            :todo="todo"
            @deleteTodo="$emit('deleteTodo', todo.id)"
        />
    </ul>
</template>
<style></style>

// learn-react/06/1/src/components/TodoList.tsx
import TodoListItem from "./TodoListItem";

export default function TodoList({
  todos,
  toggleTodo,
  deleteTodo,
}: {
  todos: { id: number; text: string; completed: boolean }[];
  toggleTodo: (id: number) => void;
  deleteTodo: (id: number) => void;
}) {
  return (
    <ul className="divide-y divide-gray-200">
      {todos.map((todo) => (
        <TodoListItem
          key={todo.id}
          todo={todo}
          toggleTodo={toggleTodo}
          deleteTodo={deleteTodo}
        />
      ))}
    </ul>
  );
}
