// learn-react/006/homework3/src/components/Todo.tsx
import { useState } from "react";
import TodoEditor from "./TodoEditor";
import TodoHeader from "./TodoHeader";
import TodoList from "./TodoList";

export default function Todo() {
  const initTodos = ["Todo Item Example", "Todo Item Example", "Todo Item Example"];
  const [todos, setTodos] = useState<string[]>(initTodos);
  const addTodo = (todo: string) => {
    setTodos((v) => [...v, todo]);
    // console.log(todo);
  };
  const deleteTodo = (index: number) => {
    setTodos((v) => v.filter((_, i) => i !== index));
  };
  return (
    <div className="w-[350px] max-w-md mx-auto shadow-lg rounded-lg overflow-hidden bg-white">
      <TodoHeader />
      <TodoEditor addTodo={addTodo} />
      <TodoList todos={todos} deleteTodo={deleteTodo} />
    </div>
  );
}

// learn-vue/student/todo_list/src/components/Todo.vue
<script>
import TodoEditor from './TodoEditor.vue';
import TodoHeader from './TodoHeader.vue';
import TodoList from './TodoList.vue';

export default {
  data() {
    return {
      todos: [],
    };
  },
  components: {
    TodoHeader,
    TodoEditor,
    TodoList,
  },
  methods: {
    addTodo(work) {
      this.todos.push({ todo: work, done: false, id: Date.now() });
      console.log(this.todos);
    },
    deleteTodo(id) {
      this.todos = this.todos.filter((todo) => todo.id !== id);
      console.log(this.todos);
    },
    doneTodo(id) {
      const selectedTodo = this.todos.find((todo) => todo.id === id);
      selectedTodo.done = !selectedTodo.done;
      console.log(this.todos);
    },
  },
};
</script>
<template>
  <div class="max-w-md mx-auto shadow-lg rounded-lg overflow-hidden">
    <TodoHeader />
    <TodoEditor @send-todo="addTodo" />
    <TodoList :todos="todos" @done-todo="doneTodo" @delete-todo="deleteTodo" />
  </div>
</template>
<style></style>
