// learn-react/06/src/components/CountButton.tsx
export default function CountButton({
  increment,
  decrement,
  reset,
}: {
  increment: () => void;
  decrement: () => void;
  reset: () => void;
}) {
  return (
    <>
      <button onClick={increment}>증가</button>
      <button onClick={reset}>리셋</button>
      <button onClick={decrement}>감소</button>
    </>
  );
}

// learn-vue/student/06/01/src/components/CountButton.vue
<script setup>
import { useCountStore } from '@/stores/count'
import { storeToRefs } from 'pinia'

const countStore = useCountStore()
const { count } = storeToRefs(countStore)
const { increment, reset, decrement } = useCountStore()
</script>
<template>
  <button @click="decrement">감소</button>
  <button @click="reset">0</button>
  <button @click="increment">증가</button>
</template>
<style scoped></style>
