// learn-vue/student/practice/todo_list_composition/src/components/TodoEditor.vue
<script setup>
import { ref } from "vue";
const text = ref("");

const emit = defineEmits(["addTodo"]);
const handleSubmit = () => {
  emit("addTodo", text.value);
  text.value = "";
};
</script>
<template>
  <form class="flex p-4" @submit.prevent="handleSubmit">
    <input
      type="text"
      v-model="text"
      placeholder="Enter a new todo"
      class="flex-grow p-2 border rounded-l-md focus:outline-none focus:ring-2 focus:ring-blue-500"
    />
    <button
      class="bg-blue-500 text-white px-4 py-2 rounded-r-md hover:bg-blue-600 transition-colors"
    >
      Add Todo
    </button>
  </form>
</template>
<style></style>

// learn-react/06/todo/src/components/TodoEditor.tsx
import { useState } from "react";

export default function TodoEditor({
  addTodo,
}: {
  addTodo: (text: string) => void;
}) {
  const [text, setText] = useState("");
  const textChangeHandler = (e: React.ChangeEvent<HTMLInputElement>) => {
    setText(e.target.value);
  };
  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    addTodo(text);
    setText("");
  };

  return (
    <form className="flex p-4" onSubmit={handleSubmit}>
      <input
        value={text}
        type="text"
        placeholder="Enter a new todo"
        className="flex-grow p-2 border rounded-l-md focus:outline-none"
        onChange={textChangeHandler}
      />
      <button className="bg-blue-500 text-white px-4 py-2 rounded-r-md hover:bg-blue-600 transition-colors">
        Add
      </button>
    </form>
  );
}
