// learn-react/06/todo/src/components/TodoList.tsx
import TodoListItem from "./TodoListItem";

export default function TodoList({
  todos,
  toggleTodo,
  deleteTodo,
}: {
  todos: TodoItem[];
  toggleTodo: (id: number) => void;
  deleteTodo: (id: number) => void;
}) {
  return (
    <ul className="divide-y divide-gray-200">
      {/* {todos.map((todo, index) => (
        <TodoListItem key={index} text={todo} />
      ))} */}
      {todos &&
        todos.map((todo) => (
          <TodoListItem
            key={todo.id}
            todo={todo}
            toggleTodo={toggleTodo}
            deleteTodo={deleteTodo}
          />
        ))}
    </ul>
  );
}

// learn-vue/student/06.todo/src/components/TodoList.vue
<script setup>
import { useTodoStore } from '@/stores/todo'
import TodoListItem from './TodoListItem.vue'
const todoStore = useTodoStore()
</script>
<template>
  <ul class="divide-y divide-gray-200">
    <TodoListItem v-for="todoItem in todoStore.todos" :key="todoItem.id" :todoItem="todoItem" />
  </ul>
</template>
<style scoped></style>
