// learn-react/06/todo/todo_useReducer/src/components/TodoList.tsx
import { ActionDispatch } from 'react';
import TodoListItem from './TodoListItem';

export default function TodoList({
  todos,
  dispatch,
}: {
  todos: TodoItem[];
  dispatch: ActionDispatch<[action: TodoReducerAction]>;
}) {
  return (
    <ul className="divide-y divide-gray-200">
      {todos &&
        todos.map((todo) => (
          <TodoListItem key={todo.id} todo={todo} dispatch={dispatch} />
        ))}
    </ul>
  );
}

// learn-vue/student/06.todo/src/components/TodoList.vue
<script setup>
import { useTodoStore } from '@/stores/todo'
import TodoListItem from './TodoListItem.vue'
const todoStore = useTodoStore()
</script>
<template>
  <ul class="divide-y divide-gray-200">
    <TodoListItem v-for="todoItem in todoStore.todos" :key="todoItem.id" :todoItem="todoItem" />
  </ul>
</template>
<style scoped></style>
