// learn_react/6/07/src/components/TodoList.tsx
import TodoListItem from "./TodoListItem";

export default function TodoList({
  input,
  deleteItem,
}: {
  input: string[];
  deleteItem: () => void;
}) {
  return (
    <ul className="divide-y divide-gray-200">
      {input.map((text, idx) => {
        return <TodoListItem key={idx} text={text} deleteItem={deleteItem} />;
      })}
    </ul>
  );
}

// learn_vue/todoList/src/components/TodoList.vue
<script setup>
import TodoListItem from './TodoListItem.vue'
import { inject } from 'vue'

const messages = inject('messages')
</script>
<template>
  <ul class="divide-y divide-gray-200">
    <TodoListItem
      v-for="message in messages"
      :key="message.id"
      :id="message.id"
      :message="message.text"
    />
  </ul>
</template>
<style></style>
