// learn-vue/student/todo_list/src/components/TodoEditor.vue
<script>
export default {
  name: "TodoEditor",
  props: ["inputText", "addClickHandler"],
};
</script>
<template>
  <div class="flex p-4">
    <input
      type="text"
      :value="inputText"
      placeholder="Enter a new todo"
      class="flex-grow p-2 border rounded-l-md focus:outline-none focus:ring-2 focus:ring-blue-500"
    />
    <button
      class="bg-blue-500 text-white px-4 py-2 rounded-r-md hover:bg-blue-600 transition-colors"
      @click="addClickHandler"
    >
      Add Todo
    </button>
  </div>
</template>
<style></style>

// learn-react/d06/p3/src/components/TodoEditor.tsx
import { useState } from "react";

export default function TodoEditor({
  addTodo,
}: {
  addTodo: (text: string) => void;
}) {
  const [input, setInput] = useState("");
  const changeHandler = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInput(e.target.value);
  };
  const addHandler = () => {
    addTodo(input);
    setInput("");
  };

  return (
    <div className="flex p-4">
      <input
        type="text"
        placeholder="Enter a new todo"
        value={input}
        onChange={changeHandler}
        className="flex-grow p-2 border rounded-l-md focus:outline-none"
      />
      <button
        className="bg-blue-500 text-white px-4 py-2 rounded-r-md hover:bg-blue-600 transition-colors"
        onClick={addHandler}
      >
        Add
      </button>
    </div>
  );
}
