// learn-react/06/1/src/App copy 2.tsx
import { useState } from "react";

export default function App() {
  const [count, setCount] = useState(0);
  return (
    <>
      <h1 className="text-3xl underline">Count: {count}</h1>
      <button onClick={() => setCount((count) => count - 1)}>감소</button>
      <button onClick={() => setCount(0)}>0(리셋)</button>
      <button onClick={() => setCount((count) => count + 1)}>증가</button>
    </>
  );
}

// learn-vue/student/02/src/App copy 2.vue
<script>
export default {
  name: 'App',
  data() {
    return {
      count: 0,
    }
  },
  methods: {
    decrement() {
      this.count -= 1
    },
    reset() {
      this.count = 0
    },
    increment() {
      this.count += 1
    },
    incrementByAmount(amount) {
      this.count += amount
    },
  },
}
</script>
<template>
  <h1>Count: {{ count }}</h1>
  <!-- 감소 -->
  <button @click="decrement">감소</button>
  <!-- 리셋 -->
  <button @click="reset">리셋</button>
  <!-- 증가 -->
  <button @click="increment">증가</button>
  <button @click="incrementByAmount(10)">증가</button>
</template>
<style scoped></style>
