// learn-react/06/1/src/components/TodoList.tsx
import TodoListItem from "./TodoListItem";

export default function TodoList({
  todos,
  toggleTodo,
  deleteTodo,
}: {
  todos: { id: number; text: string; completed: boolean }[];
  toggleTodo: (id: number) => void;
  deleteTodo: (id: number) => void;
}) {
  return (
    <ul className="divide-y divide-gray-200">
      {todos.map((todo) => (
        <TodoListItem
          key={todo.id}
          todo={todo}
          toggleTodo={toggleTodo}
          deleteTodo={deleteTodo}
        />
      ))}
    </ul>
  );
}

// learn-vue/student/practice/03.todo(composition)/src/components/TodoList.vue
<script setup>
import TodoListItem from "./TodoListItem.vue";

const props = defineProps({ todos: { type: Array } });

const emit = defineEmits(["toggleTodo", "deleteTodo"]);
const toggleTodo = (id) => emit("toggleTodo", id);
const deleteTodo = (id) => emit("deleteTodo", id);
</script>
<template>
  <ul class="divide-y divide-gray-200">
    <TodoListItem
      v-for="todo in props.todos"
      :key="todo.id"
      :todo="todo"
      @toggle-todo="toggleTodo"
      @delete-todo="deleteTodo"
    />
  </ul>
</template>
<style></style>
