// learn-vue/student/practice/todo_list_composition/src/components/Todo.vue
<script setup>
import { ref, watch, onMounted } from "vue";
import TodoEditor from "./TodoEditor.vue";
import TodoHeader from "./TodoHeader.vue";
import TodoList from "./TodoList.vue";

const todos = ref([]);
const addTodo = (text) => {
  if (text.value === null) return;
  todos.value.push({
    id: Date.now(),
    text,
    done: false,
  });
};

const toggleTodo = (id) => {
  todos.value = todos.value.map((todo) => (todo.id === id ? { ...todo, done: !todo.done } : todo));
};
const deleteTodo = (id) => {
  todos.value = todos.value.filter((todo) => todo.id !== id);
};
onMounted(() => {
  const saved = sessionStorage.getItem("todos");
  if (saved) {
    todos.value = JSON.parse(saved);
  }
});
watch(
  todos,
  (newTodos) => {
    sessionStorage.setItem("todos", JSON.stringify(newTodos));
  },
  {
    deep: true,
  }
);
</script>
<template>
  <div class="max-w-md mx-auto shadow-lg rounded-lg overflow-hidden">
    <TodoHeader />
    <TodoEditor @add-todo="addTodo" />
    <TodoList :todos="todos" @delete-todo="deleteTodo" @toggle-todo="toggleTodo" />
  </div>
</template>
<style></style>

// learn-react/todos/todo_props/src/components/Todo.tsx
import { useState } from 'react';
import TodoEditor from './TodoEditor';
import TodoHeader from './TodoHeader';
import TodoList from './TodoList';

// 일반 객체는 interface
// 타입별칭 type

export default function Todo() {
  const [todos, setTodos] = useState<TodoItem[]>([]);
  const addTodo = (text: string) => {
    setTodos((todos) => [
      ...todos,
      {
        id: Math.random(),
        text,
        done: false,
      },
    ]);
  };

  const toggleTodo = (id: number) => {
    setTodos((todos) =>
      todos.map((todo) =>
        todo.id === id ? { ...todo, done: !todo.done } : todo
      )
    );
  };

  const deleteTodo = (id: number) => {
    setTodos((todos) => todos.filter((todo) => todo.id !== id));
  };
  return (
    <div className="w-[350px] max-w-md mx-auto shadow-lg rounded-lg overflow-hidden bg-white">
      <TodoHeader />
      <TodoEditor addTodo={addTodo} />
      <TodoList todos={todos} toggleTodo={toggleTodo} deleteTodo={deleteTodo} />
    </div>
  );
}
