// learn-react/06/project3/src/components/Todo.tsx
import { useState } from "react";
import TodoEditor from "./TodoEditor";
import TodoHeader from "./TodoHeader";
import TodoList from "./TodoList";

export default function Todo() {
  const [listItem, setListItem] = useState<
    { id: number; complete: boolean; title: string }[]
  >([]);

  return (
    <div className="w-[350px] max-w-md mx-auto shadow-lg rounded-lg overflow-hidden bg-white">
      <TodoHeader />
      <TodoEditor listItem={listItem} setListItem={setListItem} />
      <TodoList listItem={listItem} setListItem={setListItem} />
    </div>
  );
}

// learn_vue/student/06/todo_pinia/src/components/Todo.vue
<script setup>
import { useTodoStore } from "../stores/todo";
import TodoEditor from "./TodoEditor.vue";
import TodoHeader from "./TodoHeader.vue";
import TodoList from "./TodoList.vue";

const todoStore = useTodoStore();
</script>
<template>
  <div class="max-w-md mx-auto shadow-lg rounded-lg overflow-hidden">
    <TodoHeader />
    <TodoEditor />
    <TodoList />
  </div>
</template>
<style></style>
