// learn-vue/student/03/src/components/CountButtons.vue
<script>
export default {
  name: 'CountButtons',
  inject: ['decrement', 'increment', 'reset', 'incrementByAmount'],
}
</script>
<template>
  <button @click="decrement">-</button>
  <button @click="reset">0</button>
  <button @click="increment">+</button>
  <button @click="incrementByAmount(10)">++</button>
</template>
<style scoped></style>

// learn-react/08/1/src/components/CountButtons.tsx
import { useCountStore } from "../stores/countStores";

export default function CountButtons() {
  const decrement = useCountStore((state) => state.decrement);
  const reset = useCountStore((state) => state.reset);
  const increment = useCountStore((state) => state.increment);
  return (
    <>
      <button onClick={decrement}>-</button>
      <button onClick={reset}>0</button>
      <button onClick={increment}>+</button>
    </>
  );
}
