// learn-react/08/1/src/components/CountButtons.tsx
import { useCountStore } from "../stores/countStores";

export default function CountButtons() {
  const decrement = useCountStore((state) => state.decrement);
  const reset = useCountStore((state) => state.reset);
  const increment = useCountStore((state) => state.increment);
  return (
    <>
      <button onClick={decrement}>-</button>
      <button onClick={reset}>0</button>
      <button onClick={increment}>+</button>
    </>
  );
}

// learn_vue/student/03/02/src/components/CountButtons.vue
<script>
export default {
  name: 'CountButtons',
  data() {
    return {}
  },
  props: {
    number: Number,
  },
  emits: ['increment', 'decrement', 'reset', 'incrementByAmount'],
}
</script>
<template>
  <button @click="$emit('decrement')">-</button>
  <button @click="$emit('reset')">0</button>
  <button @click="$emit('increment')">+</button>
  <button @click="$emit('incrementByAmount', 5)">+</button>
</template>
<style scoped></style>
