// learn-vue/student/06/src/components/CountButton.vue
<script setup>
import { useCountStore } from '@/stores/count'

const countStore = useCountStore()
</script>
<template>
  <button @click="countStore.decrement">감소</button>
  <button @click="countStore.reset">0</button>
  <button @click="countStore.increment">증가</button>
</template>
<style scoped></style>

// learn_react/state_master/src/components/state/zustand/CountButton.tsx
import { useCounterStore } from "../../../stores/counterStore";

export default function CountButton() {
  const increment = useCounterStore((state) => state.increment);
  const decrement = useCounterStore((state) => state.decrement);

  const reset = useCounterStore((state) => state.reset);

  return (
    <>
      <button onClick={decrement}>-</button>
      <button onClick={reset}>0</button>
      <button onClick={increment}>+</button>
    </>
  );
}
